import = [
  "~/.config/alacritty/dracula.toml"
]

[font]
normal = { family = "Source Code Pro", style = "Regular" }
size = 13.0

[window]
padding = { x = 4, y = 4 }
opacity = 0.95
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
