#!/bin/bash

# Ensure submodules are cloned
git submodule init && git submodule update

# Start off by symlinking the appropriate files and folders
mkdir ~./config
ln -s ./config/fish ~/.config/fish
ln -s ./config/nvim ~/.config/nvim
ln -s ./vim ~/.vim
ln -s ./vimrc ~/.vimrc
ln -s ./zshrc ~/.zshrc

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install software using Brewfile
brew bundle

# Install fish as a shell option
echo /usr/local/bin/fish | sudo tee -a /etc/shells

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
