#!/bin/bash

# Ensure submodules are cloned
git submodule init && git submodule update

# Start off by symlinking the appropriate files and folders
mkdir ~./config
ln -s config/fish ~/.config/fish
ln -s config/nvim ~/.config/nvim
ln -s vim ~/.vim
ln -s vimrc ~/.vimrc

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install software using Brewfile
brew bundle

# Install fish as a shell option
echo /usr/local/bin/fish | sudo tee -a /etc/shells

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
